
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: node_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  dbinit:
    image: postgres
    container_name: db_init
    depends_on:
      - db
    volumes:
      - ./backend/src/schemas/deimos.dump:/deimos.dump
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    entrypoint: ["sh", "/docker-entrypoint-initdb.d/init-db.sh"]

volumes:
  postgres_data:
