name: Merge Specific Folders

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  merge-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge Backend Changes
        run: |
          git checkout backend -- Scrum/backend
          git status # Verifica el estado después de la fusión de la carpeta backend

      - name: Merge Frontend Changes
        run: |
          git checkout dev -- Scrum/fronted
          git status # Verifica el estado después de la fusión de la carpeta frontend

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Scrum/backend Scrum/fronted
          git commit -m "Merged specific folders from backend and dev"

      - name: Check Git Status Before Push
        run: |
          git status # Verifica el estado antes de hacer push

      - name: Push Changes
        run: |
          git push origin main
