name: Run tests

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.1

      - name: Install Dependencies
        run: cd Scrum/backend && npm install
      - name: Run tests
        run: cd Scrum/backend && npm test